---
title: "Run models"
author: "Stefano Coretta"
format: html
---

## Set-up

```{r}
#| label: setup

library(tidyverse)
library(brms)

sim_data <- readRDS("sim_data.rds")

sim_data <- sim_data |> 
  mutate(
    sv = as.factor(paste0(v, ".", s))
  )
my_seed <- 1911
```

## BM 1 with indexing

### Prior

```{r}
#| label: bm-1-bf

bm_1_bf <- bf(
  dv ~ 0 + sv + (0 + sv | subj)
)
```

```{r}
#| label: bm-1-prior

bm_1_priors_default <- get_prior(
  bm_1_bf,
  data = sim_data
)

bm_1_priors <- bm_1_priors_default |> 
  mutate(
    prior = ifelse(
      prior == "" & class == "b" & coef != "", "normal(0, 5)", prior
    )
  )

bm_1_prior_pp <- brm(
  bm_1_bf,
  data = sim_data,
  prior = bm_1_priors,
  sample_prior = "only",
  cores = 4,
  backend = "cmdstanr",
  seed = my_seed
)
```

```{r}
#| label: bm-1-prior-cond
conditional_effects(bm_1_prior_pp)
```

### Run

```{r}
#| label: bm-1

bm_1 <- brm(
  bm_1_bf,
  data = sim_data,
  cores = 4,
  backend = "cmdstanr",
  seed = my_seed
)
```

```{r}
#| label: bm-1-sum
bm_1
```

```{r}
#| label: bm-1-cond
conditional_effects(bm_1)
```

## BM1a with indexing

```{r}
#| label: bm-1a-bf

bm_1a_bf <- bf(
  dv ~ 0 + s:v + (0 + s:v | subj)
)
```

```{r}
#| label: bm-1a-prior

bm_1a_priors_default <- get_prior(
  bm_1a_bf,
  data = sim_data
)

bm_1a_priors <- bm_1a_priors_default |> 
  mutate(
    prior = ifelse(
      prior == "" & class == "b" & coef != "", "normal(0, 5)", prior
    )
  )

bm_1a_prior_pp <- brm(
  bm_1a_bf,
  data = sim_data,
  prior = bm_1a_priors,
  sample_prior = "only",
  cores = 4,
  backend = "cmdstanr",
  seed = my_seed
)
```

```{r}
#| label: bm-1a-prior-cond
conditional_effects(bm_1a_prior_pp)
```

```{r}
#| label: bm-1a

bm_1a <- brm(
  bm_1a_bf,
  data = sim_data,
  cores = 4,
  backend = "cmdstanr",
  seed = my_seed
)
```

```{r}
#| label: bm-1a-sum
bm_1a
```

```{r}
#| label: bm-1a-cond
conditional_effects(bm_1a, "v:s")
```

## BM2 with contrasts

### Prior

```{r}
#| label: bm-2-bf

bm_2_bf <- bf(
  dv ~ s*v + (s*v | subj)
)
```

```{r}
#| label: bm-2-prior

bm_2_priors_default <- get_prior(
  bm_2_bf,
  data = sim_data
)

bm_2_priors <- bm_2_priors_default |> 
  mutate(
    prior = ifelse(
      prior == "" & class == "b" & coef != "", "normal(0, 5)", prior
    )
  )

bm_2_prior_pp <- brm(
  dv ~ s*v + (s*v | subj),
  data = sim_data,
  prior = bm_2_priors,
  sample_prior = "only",
  cores = 4,
  backend = "cmdstanr",
  seed = my_seed
)
```

```{r}
#| label: bm-2-prior-cond
conditional_effects(bm_2_prior_pp, "v:s")
```

### Run

```{r}
#| label: bm-2
bm_2 <- brm(
  dv ~ s*v + (s*v | subj),
  data = sim_data,
  cores = 4,
  backend = "cmdstanr"
)
bm_2
```

```{r}
#| label: bm-2-cond
conditional_effects(bm_2, "v:s")
```

## BM1-NL

```{r}
bm_1_nl_bf <- bf(
    dv ~ 0 + a,
    a ~ 0 + sv + (0 + sv |p| subj),
    nl = TRUE
  )

bm_1_nl_priors_default <- get_prior(
  bm_1_nl_bf,
  data = sim_data
)

bm_1_nl_priors <- bm_1_nl_priors_default |> 
  mutate(
    prior = ifelse(prior == "" & class == "b" & coef != "", "normal(0, 5)", prior)
  )


bm_1_nl <- brm(
  bm_1_nl_bf,
  data = sim_data,
  prior = bm_1_nl_priors,
  chains = 1,
  backend = "cmdstanr"
)

bm_1_nl
conditional_effects(bm_1_nl, "sv")
```

```{r}
ranef(bm_1_nl)
```
